package server.httpserver.dao;

import server.httpserver.pojo.CronTriggersBean;
import server.httpserver.pojo.CronTriggersBeanKey;

public interface CronTriggersBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CRON_TRIGGERS
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(CronTriggersBeanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CRON_TRIGGERS
     *
     * @mbggenerated
     */
    int insert(CronTriggersBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CRON_TRIGGERS
     *
     * @mbggenerated
     */
    int insertSelective(CronTriggersBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CRON_TRIGGERS
     *
     * @mbggenerated
     */
    CronTriggersBean selectByPrimaryKey(CronTriggersBeanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CRON_TRIGGERS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CronTriggersBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CRON_TRIGGERS
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CronTriggersBean record);
}