package server.httpserver.dao;

import server.httpserver.pojo.LocksBeanKey;

public interface LocksBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_LOCKS
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(LocksBeanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_LOCKS
     *
     * @mbggenerated
     */
    int insert(LocksBeanKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_LOCKS
     *
     * @mbggenerated
     */
    int insertSelective(LocksBeanKey record);
}