package server.httpserver.pojo;

import java.io.Serializable;

public class CronTriggersBean extends CronTriggersBeanKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_CRON_TRIGGERS.CRON_EXPRESSION
     *
     * @mbggenerated
     */
    private String cronExpression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_CRON_TRIGGERS.TIME_ZONE_ID
     *
     * @mbggenerated
     */
    private String timeZoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table QRTZ_CRON_TRIGGERS
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_CRON_TRIGGERS.CRON_EXPRESSION
     *
     * @return the value of QRTZ_CRON_TRIGGERS.CRON_EXPRESSION
     *
     * @mbggenerated
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_CRON_TRIGGERS.CRON_EXPRESSION
     *
     * @param cronExpression the value for QRTZ_CRON_TRIGGERS.CRON_EXPRESSION
     *
     * @mbggenerated
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression == null ? null : cronExpression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_CRON_TRIGGERS.TIME_ZONE_ID
     *
     * @return the value of QRTZ_CRON_TRIGGERS.TIME_ZONE_ID
     *
     * @mbggenerated
     */
    public String getTimeZoneId() {
        return timeZoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_CRON_TRIGGERS.TIME_ZONE_ID
     *
     * @param timeZoneId the value for QRTZ_CRON_TRIGGERS.TIME_ZONE_ID
     *
     * @mbggenerated
     */
    public void setTimeZoneId(String timeZoneId) {
        this.timeZoneId = timeZoneId == null ? null : timeZoneId.trim();
    }
}