package server.httpserver.pojo;

import java.io.Serializable;

public class JobDetailsBean extends JobDetailsBeanKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_JOB_DETAILS.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_JOB_DETAILS.JOB_CLASS_NAME
     *
     * @mbggenerated
     */
    private String jobClassName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_JOB_DETAILS.IS_DURABLE
     *
     * @mbggenerated
     */
    private String isDurable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_JOB_DETAILS.IS_NONCONCURRENT
     *
     * @mbggenerated
     */
    private String isNonconcurrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_JOB_DETAILS.IS_UPDATE_DATA
     *
     * @mbggenerated
     */
    private String isUpdateData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_JOB_DETAILS.REQUESTS_RECOVERY
     *
     * @mbggenerated
     */
    private String requestsRecovery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_JOB_DETAILS.JOB_DATA
     *
     * @mbggenerated
     */
    private byte[] jobData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table QRTZ_JOB_DETAILS
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_JOB_DETAILS.DESCRIPTION
     *
     * @return the value of QRTZ_JOB_DETAILS.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_JOB_DETAILS.DESCRIPTION
     *
     * @param description the value for QRTZ_JOB_DETAILS.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_JOB_DETAILS.JOB_CLASS_NAME
     *
     * @return the value of QRTZ_JOB_DETAILS.JOB_CLASS_NAME
     *
     * @mbggenerated
     */
    public String getJobClassName() {
        return jobClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_JOB_DETAILS.JOB_CLASS_NAME
     *
     * @param jobClassName the value for QRTZ_JOB_DETAILS.JOB_CLASS_NAME
     *
     * @mbggenerated
     */
    public void setJobClassName(String jobClassName) {
        this.jobClassName = jobClassName == null ? null : jobClassName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_JOB_DETAILS.IS_DURABLE
     *
     * @return the value of QRTZ_JOB_DETAILS.IS_DURABLE
     *
     * @mbggenerated
     */
    public String getIsDurable() {
        return isDurable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_JOB_DETAILS.IS_DURABLE
     *
     * @param isDurable the value for QRTZ_JOB_DETAILS.IS_DURABLE
     *
     * @mbggenerated
     */
    public void setIsDurable(String isDurable) {
        this.isDurable = isDurable == null ? null : isDurable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_JOB_DETAILS.IS_NONCONCURRENT
     *
     * @return the value of QRTZ_JOB_DETAILS.IS_NONCONCURRENT
     *
     * @mbggenerated
     */
    public String getIsNonconcurrent() {
        return isNonconcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_JOB_DETAILS.IS_NONCONCURRENT
     *
     * @param isNonconcurrent the value for QRTZ_JOB_DETAILS.IS_NONCONCURRENT
     *
     * @mbggenerated
     */
    public void setIsNonconcurrent(String isNonconcurrent) {
        this.isNonconcurrent = isNonconcurrent == null ? null : isNonconcurrent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_JOB_DETAILS.IS_UPDATE_DATA
     *
     * @return the value of QRTZ_JOB_DETAILS.IS_UPDATE_DATA
     *
     * @mbggenerated
     */
    public String getIsUpdateData() {
        return isUpdateData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_JOB_DETAILS.IS_UPDATE_DATA
     *
     * @param isUpdateData the value for QRTZ_JOB_DETAILS.IS_UPDATE_DATA
     *
     * @mbggenerated
     */
    public void setIsUpdateData(String isUpdateData) {
        this.isUpdateData = isUpdateData == null ? null : isUpdateData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_JOB_DETAILS.REQUESTS_RECOVERY
     *
     * @return the value of QRTZ_JOB_DETAILS.REQUESTS_RECOVERY
     *
     * @mbggenerated
     */
    public String getRequestsRecovery() {
        return requestsRecovery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_JOB_DETAILS.REQUESTS_RECOVERY
     *
     * @param requestsRecovery the value for QRTZ_JOB_DETAILS.REQUESTS_RECOVERY
     *
     * @mbggenerated
     */
    public void setRequestsRecovery(String requestsRecovery) {
        this.requestsRecovery = requestsRecovery == null ? null : requestsRecovery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_JOB_DETAILS.JOB_DATA
     *
     * @return the value of QRTZ_JOB_DETAILS.JOB_DATA
     *
     * @mbggenerated
     */
    public byte[] getJobData() {
        return jobData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_JOB_DETAILS.JOB_DATA
     *
     * @param jobData the value for QRTZ_JOB_DETAILS.JOB_DATA
     *
     * @mbggenerated
     */
    public void setJobData(byte[] jobData) {
        this.jobData = jobData;
    }
}