package server.httpserver.pojo;

import java.io.Serializable;

public class SchedulerStateBean extends SchedulerStateBeanKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME
     *
     * @mbggenerated
     */
    private Long lastCheckinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL
     *
     * @mbggenerated
     */
    private Long checkinInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table QRTZ_SCHEDULER_STATE
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME
     *
     * @return the value of QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME
     *
     * @mbggenerated
     */
    public Long getLastCheckinTime() {
        return lastCheckinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME
     *
     * @param lastCheckinTime the value for QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME
     *
     * @mbggenerated
     */
    public void setLastCheckinTime(Long lastCheckinTime) {
        this.lastCheckinTime = lastCheckinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL
     *
     * @return the value of QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL
     *
     * @mbggenerated
     */
    public Long getCheckinInterval() {
        return checkinInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL
     *
     * @param checkinInterval the value for QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL
     *
     * @mbggenerated
     */
    public void setCheckinInterval(Long checkinInterval) {
        this.checkinInterval = checkinInterval;
    }
}