package server.httpserver.pojo;

import java.io.Serializable;

public class SchedulerStateBeanKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_SCHEDULER_STATE.SCHED_NAME
     *
     * @mbggenerated
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_SCHEDULER_STATE.INSTANCE_NAME
     *
     * @mbggenerated
     */
    private String instanceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table QRTZ_SCHEDULER_STATE
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_SCHEDULER_STATE.SCHED_NAME
     *
     * @return the value of QRTZ_SCHEDULER_STATE.SCHED_NAME
     *
     * @mbggenerated
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_SCHEDULER_STATE.SCHED_NAME
     *
     * @param schedName the value for QRTZ_SCHEDULER_STATE.SCHED_NAME
     *
     * @mbggenerated
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName == null ? null : schedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_SCHEDULER_STATE.INSTANCE_NAME
     *
     * @return the value of QRTZ_SCHEDULER_STATE.INSTANCE_NAME
     *
     * @mbggenerated
     */
    public String getInstanceName() {
        return instanceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_SCHEDULER_STATE.INSTANCE_NAME
     *
     * @param instanceName the value for QRTZ_SCHEDULER_STATE.INSTANCE_NAME
     *
     * @mbggenerated
     */
    public void setInstanceName(String instanceName) {
        this.instanceName = instanceName == null ? null : instanceName.trim();
    }
}